### ISSUE TITLE
Please disable and fix this application immediately

### ISSUE THREAD

**Issue by topaz** [jocoone/adventofcodedashboard#2]
Hi! Creator of Advent of Code here.  This seems to be the repo for `adventofcode.javaxxes.com`.

Whenever any user opens this application, their browser sends requests to the AoC servers as fast as it can, causing a significant increase in traffic.

**I have banned your account from Advent of Code** to try to decrease the effect of the traffic.  Please disable this application ASAP, then fix it.  When it's fixed, **email me with the code diff of the fix to have your account unbanned**: http://was.tl/contact/

Also, the source code of this application contains your session cookie, allowing any user to log in as you.  You'll want to rethink the architecture of your application to avoid releasing your credentials to the public.

**Comment by jocoone** [comment]
Removed entire application and automatic refresh. The session cookie should work in the current setup and only use the cookie from the user itself. But removed the deployed application either way. Sorry for the inconvenience.

**Comment by topaz** [comment]
I've unbanned your account.  In the future, please please check that your application is behaving before pointing it at the AoC servers.

**Comment by topaz** [comment]
Also, if this is the commit you're referring to, I don't see where you disable auto-refresh: https://github.com/jocoone/adventofcodedashboard/commit/607d0cd61058a44a2dfe7d4950e8f9402d68c6ce?w=1

**Comment by jocoone** [comment]
Yeah Sorry, Because the autorefresh was never commited in the repo. I build it locally on my machine and then deployed it manually. Is it still possibble that my IP address is still blocked because I still cant reach: https://adventofcode.com?

**Comment by jocoone** [comment]
I only made this repo because some people in my company wanted to take a look on HOW I did it.

**Comment by topaz** [comment]
The only IPs I've blocked recently are Amazon IPs; reverse DNS reports `*.cloudfront.net`.  Assuming you're not CloudFront, feel free to send me your IP and I can take a look: http://was.tl/contact/
